name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show buildozer.spec content
        run: cat buildozer.spec
           - name: Build with buildozer
        run: yes | buildozer android debug --verbose --log_level=2
      - name: Test gradle build
      run: |
        cd .buildozer/android/platform/build-arm64-v8a/dists/horsebless
        chmod +x gradlew
       ./gradlew clean assembleDebug --stacktrace
      continue-on-error: true   # 即使失败也继续，方便查看日志  

      - name: Deep inspect buildozer.spec
        run: |
          echo "=== File encoding ==="
          file buildozer.spec
          echo "=== Line numbers and content ==="
          cat -n buildozer.spec
          echo "=== Search for version.regex ==="
          grep -n "version.regex" buildozer.spec || echo "No version.regex found"
          echo "=== Search for version.filename ==="
          grep -n "version.filename" buildozer.spec || echo "No version.filename found"
          echo "=== Search for version = (without comment) ==="
          grep -n "^version =" buildozer.spec || echo "No active version line found"

      - name: Accept Android licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

     - name: Install Android SDK components
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"   

      - name: Force remove any version.regex lines (just in case)
        run: |
          sed -i '/version\.regex/d' buildozer.spec
          sed -i '/version\.filename/d' buildozer.spec
          echo "=== After forced removal ==="
          cat buildozer.spec
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '11'    

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 \
            cmake libffi-dev libssl-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
          echo "KEYSTORE_FILE=$(pwd)/keystore.jks" >> $GITHUB_ENV

      - name: Set signature environment variables
        run: |
          echo "KEYSTORE_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEYSTORE_PASS=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "KEYALIAS_PASS=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Clean buildozer cache (optional)
        run: rm -rf ~/.buildozer

      - name: Build with buildozer
        run: yes | buildozer android debug --log_level=2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: bin/*.apk





