name: Build Kivy APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython
      - name: Cache buildozer
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
      - name: Build with buildozer
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
      - name: Clean build cache
        run: rm -rf ~/.buildozer  
        with:
          name: app-debug

          path: bin/*.apk
