name: Build Signed Kivy APK

on: [workflow_dispatch, push]  # 你可以根据需要调整触发条件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # ---------- 关键步骤 1: 解码并创建 keystore 文件 ----------
      - name: Decode Keystore
        env:
          # 这个签名字段需要您先在 GitHub Secrets 里创建
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # 将 Secrets 中保存的 base64 字符串解码，还原为原始的 keystore 文件
          echo "$KEYSTORE_BASE64" | base64 --decode > ./my-release-key.keystore
      # -------------------------------------------------------

      # ---------- 关键步骤 2: 将签名信息设为环境变量 ----------
      - name: Set Signing Environment Variables
        run: |
          # 这些 Secrets 也需要您在 GitHub 上预先设置好
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
      # -------------------------------------------------------

      - name: Build with buildozer
        run: |
          yes | buildozer android release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-debug
          path: bin/*.apk
